### ISSUE TITLE
PHP Track Courses to be completed

### ISSUE THREAD

**Issue by chris1hum** [chris1hum/git-learning#2]
## TODO

*Courses left to complete the Treehouse PHP Track*

* [x] PHP Functions
* [x] PHP:Installing a Local Dev Environment
* [ ] Basic Error Handling in PHP
* [ ] Build a Basic PHP Website

:tada: :ok_man: :confetti_ball:

cc @chris1hum
